### ISSUE TITLE
Please update sentry

### ISSUE THREAD

**Issue by popey** [snapcrafters/sentry#1]
There's a new upstream version of sentry - 8.19 Please update the yaml accordingly. Thanks.

**Comment by Ads20000** [comment]
Would it just require changing the version number in the yaml? I have no idea how to go about testing it if we have to test it... The build is failing as per #2 anyway...

**Comment by Ads20000** [comment]
Would best practice be to update the yaml, promote to `candidate` if it builds successfully, then ask for confirmation it works from someone before promoting to `stable`?

**Comment by popey** [comment]
@Ads20000 yeah, that's what I've been doing for other snaps.

**Comment by popey** [comment]
This was fixed by https://github.com/snapcrafters/sentry/commit/b664fdd1378c5a244124d22138384e95bacbfbb7
