### ISSUE TITLE
Mail configuration after install not working 

### ISSUE THREAD

**Issue by nisamudeen97** [snapcrafters/sentry#15]
Hi,

We have installed good using this documentation meanwhile we have updated the SMTP settings after installation via admin page.  Meanwhile while sending test email it is showing the below error

>>    character mapping must return integer, None or unicode

**Comment by merlijn-sebrechts** [comment]
Is this issue still present in the latest version of this snap?

**Comment by merlijn-sebrechts** [comment]
Closing this issue as it's likely fixed in the last version. Please re-open if this is not the case!
