### ISSUE TITLE
10.0.0 fails to build due to missing sentry-plugins

### ISSUE THREAD

**Issue by popey** [snapcrafters/sentry#27]
`ERROR: Could not find a version that satisfies the requirement sentry-plugins==10.0.0 (from versions: 8.10.0, 8.11.0, 8.12.0, 8.13.0, 8.14.0, 8.14.1, 8.15.0, 8.16.0, 8.16.1, 8.17.0, 8.18.0, 8.19.0, 8.20.0, 8.21.0, 8.22.0, 9.0.0rc1, 9.0.0, 9.1.0, 9.1.1, 9.1.2)`

from https://launchpadlibrarian.net/460125287/buildlog_snap_ubuntu_bionic_amd64_17fc91e19f932bd8a75175923b533019_BUILDING.txt.gz

**Comment by salty-horse** [comment]
Is this still blocking the packaging of the sentry 10 snap?

**Comment by jamesbeedy** [comment]
[Plugins are now maintained in the upstream sentry project](https://github.com/getsentry/sentry/tree/460817810c0a62b81218a15903a56563bdc19844/src/sentry_plugins)

[Also see the deprecated sentry-plugins repo here](https://github.com/getsentry/sentry-plugins)
