### ISSUE TITLE
Consider changing `contact` field

### ISSUE THREAD

**Issue by Ads20000** [snapcrafters/sentry#3]
Sentry's `contact` field is currently for upstream (`https://github.com/getsentry/sentry/issues
`). Given the snap is distributed by us, not by upstream, the `contact` field should probably be `https://github.com/snapcrafters/sentry/issues` until we are able to transfer the snap.

**Comment by popey** [comment]
Blocked by: https://launchpad.net/bugs/1692037

**Comment by popey** [comment]
Fixed.
