### ISSUE TITLE
apparmor blocks startup

### ISSUE THREAD

**Issue by Mikki-black** [snapcrafters/sentry#33]
Hello,

I seem to have an issue with this snap both stable and edge that blocks it from starting although it worked just fine for a couple of months:
[Wed Apr  7 09:49:17 2021] audit: type=1400 audit(1617781758.936:18): apparmor="DENIED" operation="open" profile="snap.sentry.web" name="/proc/425/mounts" pid=425 comm="python2" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[Wed Apr  7 09:49:17 2021] audit: type=1400 audit(1617781758.940:19): apparmor="DENIED" operation="open" profile="snap.sentry.worker" name="/proc/429/mounts" pid=429 comm="python2" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[Wed Apr  7 09:49:17 2021] audit: type=1400 audit(1617781758.952:20): apparmor="DENIED" operation="open" profile="snap.sentry.cron" name="/proc/443/mounts" pid=443 comm="python2" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[Wed Apr  7 09:49:18 2021] audit: type=1400 audit(1617781759.416:21): apparmor="DENIED" operation="open" profile="snap.sentry.worker" name="/root/snap/sentry/70/.sentry/sentry.conf.py" pid=429 comm="python2" requested_mask="r" denied_mask="r" fsuid=0 ouid=33
[Wed Apr  7 09:49:18 2021] audit: type=1400 audit(1617781759.416:22): apparmor="DENIED" operation="open" profile="snap.sentry.cron" name="/root/snap/sentry/70/.sentry/sentry.conf.py" pid=443 comm="python2" requested_mask="r" denied_mask="r" fsuid=0 ouid=33
[Wed Apr  7 09:49:18 2021] audit: type=1400 audit(1617781759.416:23): apparmor="DENIED" operation="open" profile="snap.sentry.web" name="/root/snap/sentry/70/.sentry/sentry.conf.py" pid=425 comm="python2" requested_mask="r" denied_mask="r" fsuid=0 ouid=33

I can't seem to figure out why apparmor denies it. I tried to change it to complain, but that seems to fail to find the profile:
aa-complain snap.sentry.web 
Profile for /var/lib/snapd/apparmor/profiles/snap.sentry.web not found, skipping
Apparmor is not my strong point :\. Any ideas?

**Comment by merlijn-sebrechts** [comment]
Is this issue still present in the latest version of the snap?

**Comment by merlijn-sebrechts** [comment]
Closing this issue as it's likely fixed in the last version. Please re-open if this is not the case!
