### ISSUE TITLE
Stable version bumped to v21.2

### ISSUE THREAD

**Issue by Pheasey** [snapcrafters/sentry#41]
### What changes would you like?

Before May 12th the stable version of the snap was listed as 9.1.2 which was the only stable release since July 2019, this was recently bumped to 21.2 which I have reverted back to 9 locally until I can figure out the below.

Sentry lists a few [hard stops](https://develop.sentry.dev/self-hosted/releases/#hard-stops) on their documentation in order to migrate data between versions. Do stable (or stable enough edge version) exist for these intermediary points? Or would I need to migrate the data outside of the snap environment (or start a fresh)?

If special steps are needed to update should this be documented?

The recent stable version bump seems to be out of the blue and there are to be a few GitHub issues open questioning the stability of previous v21 releases is this now stable?

**Comment by merlijn-sebrechts** [comment]
In terms of hard stops, this is what I find:

```
<your.sentry.version> -> 9.1.2 -> 21.5.0 -> 21.6.3 -> latest
```

So going from 9.1.2 to 21.2 should not be an issue. If I understood correctly how these hard stops work, you should be able to upgrade without any issues from that perspective. Do you agree? I can't comment on the stability of v21 releases however. We're working on releasing more versions, so you might want to wait until those come out.

We're working on a bunch of pull requests which add versions [`21.5.0`](https://github.com/snapcrafters/sentry/pull/46) and [`21.6.3`](https://github.com/snapcrafters/sentry/pull/47) and force the snap to upgrade to those versions before upgrading to [higher versions](https://github.com/snapcrafters/sentry/pull/45).

**Comment by merlijn-sebrechts** [comment]
So to summarize: the stable channel should ensure you follow the hard stops. There should not be any danger to update.
