### ISSUE TITLE
[Enhancement]: New version?

### ISSUE THREAD

**Issue by lindnerdaniel** [snapcrafters/sentry#44]
### What changes would you like?

Hi,

could you please publish a new version for snap? (from master)
My system needs the privated shared memory settings:
https://snapcraft.io/blog/private-shared-memory-support-for-snaps

Thanks and BR

Daniel

**Comment by galgalesh** [comment]
@diddledani can you do this? Feel free to add me `merlijn.sebrechts@gmail.com` as a collaborator to the snap. I'm happy to help out.

**Comment by merlijn-sebrechts** [comment]
Thanks for your bug report!

A new version of 21.2.0 is now in the `edge` channel. We'll soon promote this to stable.
